name: Publish on Push

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 23

      - name: Install dependencies
        run: npm ci

      - name: Test project
        run: npm t

      - name: Build project
        run: npm run build

      - name: Debug
        run: |
          echo "${{ secrets.NPM_USERNAME }}" | cut -c 1-3

      - name: Publish to npm
        run: |
          echo "registry=https://packages.atlassian.com/api/npm/npm-public/" >> ~/.npmrc
          echo "@atlassian:registry=https://packages.atlassian.com/api/npm/npm-public/" >> ~/.npmrc
          echo "//packages.atlassian.com/api/npm/npm-public/:username=${{ secrets.NPM_USERNAME }}" >> ~/.npmrc
          echo "//packages.atlassian.com/api/npm/npm-public/:_password=${{ secrets.NPM_PASSWORD }}" >> ~/.npmrc
          echo "//packages.atlassian.com/api/npm/npm-public/:email=zxu2@atlassian.com" >> ~/.npmrc
          echo "//packages.atlassian.com/api/npm/npm-public/:always-auth=true" >> ~/.npmrc

          npm publish
