name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
        contents: read
        id-token: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 23

      - name: Install dependencies
        run: npm ci

      - name: Test project
        run: npm t

      - name: Build project
        run: npm run build

      - name: Get NPM Publish Token
        id: publish-token
        uses: atlassian-labs/artifact-publish-token@v1.0.1
        with:
          output-modes: environment

      - name: Configure .npmrc for publishing
        run: |
          echo "@atlassian:registry=https://packages.atlassian.com/artifactory/api/npm/npm-public/" >> ~/.npmrc
          echo "//packages.atlassian.com/api/npm/npm-public/:_password=${{ secrets.ARTIFACTORY_API_KEY }}" >> ~/.npmrc
          echo "//packages.atlassian.com/api/npm/npm-public/:username=${{secrets.ARTIFACTORY_USERNAME}}" >> ~/.npmrc
          echo "//packages.atlassian.com/api/npm/npm-public/:email=zxu2@atlassian.com" >> ~/.npmrc
          echo "//packages.atlassian.com/api/npm/npm-public/:always-auth=true" >> ~/.npmrc
          chmod 600 ~/.npmrc
      - name: Publish package
        run: npm publish
