name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    name: Create release
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 23

      - name: Install dependencies
        run: npm ci

      - name: Test project
        run: npm t

      - name: Build project
        run: npm run build

      - name: Get NPM Publish Token
        id: publish-token
        uses: atlassian-labs/artifact-publish-token@v1.0.1
        with:
          output-modes: environment

      - name: Configure npmrc for Artifactory
        env:
          ARTIFACTORY_USERNAME: ${{ env.ARTIFACTORY_USERNAME }}
          ARTIFACTORY_API_KEY: ${{ env.ARTIFACTORY_API_KEY }}
        run: |
          echo "//packages.atlassian.com/npm/:_auth = ${ARTIFACTORY_USERNAME}:${ARTIFACTORY_API_KEY}" > .npmrc

      - name: Debug Configuration
        run: |
          echo "Username: $ARTIFACTORY_USERNAME"
          echo "API Key: $ARTIFACTORY_API_KEY"
          cat .npmrc
        env:
          ARTIFACTORY_USERNAME: ${{ env.ARTIFACTORY_USERNAME }}
          ARTIFACTORY_API_KEY: ${{ env.ARTIFACTORY_API_KEY }}

      - name: Publish NPM Package
        run: npm publish --registry https://packages.atlassian.com/api/npm/npm-public
