name: Release

on:
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      id-token: write
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version-file: ".nvmrc"

      - name: Install dependencies
        run: npm ci

      - name: Get Artifact Publish Token
        uses: atlassian-labs/artifact-publish-token@v1.0.1
        with:
          output-modes: npm

      - name: Publish to npm
        run: npm publish --userconfig .npmrc-public

      - name: Create GitHub Release
        env:
          GH_TOKEN: ${{ github.token }}
        run: gh release create "$(git describe --tags --abbrev=0)" --generate-notes
