name: Publish on Push

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
        contents: read
        id-token: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 23

      - name: Install dependencies
        run: npm ci

      - name: Test project
        run: npm t

      - name: Build project
        run: npm run build

      - name: Get NPM Publish Token
        id: publish-token
        uses: atlassian-labs/artifact-publish-token@v1.0.1
        with:
          output-modes: environment

      - name: Configure .npmrc-public
        run: |
          # Encode API key in base64
          ARTIFACTORY_API_KEY_ENCODED=$(echo -n ${{ secrets.ARTIFACTORY_API_KEY }} | base64)
          # Create .npmrc-public file
          cat > .npmrc-public << EOF
          registry=https://packages.atlassian.com/api/npm/npm-public/
          @atlassian:registry=https://packages.atlassian.com/api/npm/npm-public/
          //packages.atlassian.com/api/npm/npm-public/:username=${{ secrets.ARTIFACTORY_USERNAME }}
          //packages.atlassian.com/api/npm/npm-public/:_password=${{ secrets.ARTIFACTORY_API_KEY_ENCODED}}
          //packages.atlassian.com/api/npm/npm-public/:email=${{ secrets.ARTIFACTORY_USERNAME }}@atlassian.com
          //packages.atlassian.com/api/npm/npm-public/:always-auth=true
          EOF
          mv .npmrc-public ~/.npmrc-public
          chmod 600 ~/.npmrc-public
          cp ~/.npmrc-public ~/.npmrc

      - name: Publish package
        run: npm publish
